title: مقامات الحريري
description: مجموعة مقامات الحريري
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  maqamat:
    output: true
    permalink: /:collection/:name/

# Toggle
explain: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "maqamat"
    values:
      layout: "maqama"
